### ISSUE TITLE
AttributeError while rendering image scale

### ISSUE THREAD

**Issue by hvelarde** [zopefoundation/five.pt#5] opened 2015-08-11 22:32 UTC
Plone 4.3.6
five.pt 2.2.3

rendering the following template:

```xml
<div id="media" tal:condition="context/getImage">
  <img tal:replace="structure context/@@images/image/large" />
  <p class="discreet"
      tal:condition="context/imageCaption"
      tal:content="context/imageCaption">
    Image Caption
  </p>
</div>
```

causes the following exception:

```python
2015-08-11 19:13:21 ERROR plone.app.viewletmanager rendering of plone.abovecontentbody in collective.nitf.image fails: 'tuple' object has no attribute 'pop'

 - Expression: "context/@@images/image/large"
 - Filename:   ... tive.nitf/src/collective/nitf/browser/templates/image.pt
 - Location:   (line 2: col 30)
 - Source:     ... replace="structure context/@@images/image/large" />
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fe0bf278c90>
               views: <ViewMapper - at 0x7fe0bd471750>
               modules: <instance - at 0x7fe0c8a96c20>
               args: <tuple - at 0x7fe0d34b7050>
               here: <ImplicitAcquisitionWrapper cresce-o-numero-de-conflitos-e-a-violencia-no-campo-e-a-justica at 0x7fe0c239caa0>
               user: <ImplicitAcquisitionWrapper - at 0x7fe0c1c655f0>
               nothing: <NoneType - at 0x7ad090>
               container: <ImplicitAcquisitionWrapper cresce-o-numero-de-conflitos-e-a-violencia-no-campo-e-a-justica at 0x7fe0c239caa0>
               request: <instance - at 0x7fe0c128eea8>
               wrapped_repeat: <SafeMapping - at 0x7fe0c0667f70>
               traverse_subpath: <list - at 0x7fe0bd342200>
               default: <object - at 0x7fe0d348db30>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper cresce-o-numero-de-conflitos-e-a-violencia-no-campo-e-a-justica at 0x7fe0c239caa0>
               view: <SimpleViewletClass from /home/hvelarde/simples/XYZ/src/collective.nitf/src/collective/nitf/browser/templates/image.pt collective.nitf.image at 0x7fe0bd45fe50>
               translate: <function translate at 0x7fe0bd32a2a8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fe0c1797910>
               options: {...} (0)
               target_language: pt_BR
Traceback (most recent call last):
  File "/home/hvelarde/.buildout/eggs/plone.app.viewletmanager-2.0.8-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/hvelarde/.buildout/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in __call__
    return self.index(*args, **kw)
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/hvelarde/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/hvelarde/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/hvelarde/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/hvelarde/.buildout/eggs/z3c.pt-2.2.3-py2.7.egg/z3c/pt/pagetemplate.py", line 149, in render
    return base_renderer(**context)
  File "/home/hvelarde/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/hvelarde/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/hvelarde/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "/home/hvelarde/simples/XYZ/var/chameleon-cache/050b09e2d39c4cbadb7a720bacda1307.py", line 110, in render
    __cache_140603222778256 = _static_140603294958160(getitem('context'), econtext, True, ('@@images', 'image', 'large', ))
  File "/home/hvelarde/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 154, in __call__
    base = self.traverse(base, request, path_items)
  File "/home/hvelarde/.buildout/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py", line 126, in traverse
    base, name, path_items[i:], request=request
  File "/home/hvelarde/.buildout/eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/adapters.py", line 136, in traversePathElement
    return traversable.traverse(nm, further_path)
  File "/home/hvelarde/.buildout/eggs/plone.app.imaging-1.0.11-py2.7.egg/plone/app/imaging/scaling.py", line 83, in traverse
    image = self.scale(name, furtherPath.pop())
AttributeError: 'tuple' object has no attribute 'pop'

 - Expression: "context/@@images/image/large"
 - Filename:   ... tive.nitf/src/collective/nitf/browser/templates/image.pt
 - Location:   (line 2: col 30)
 - Source:     ... replace="structure context/@@images/image/large" />
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fe0bf278c90>
               views: <ViewMapper - at 0x7fe0bd471750>
               modules: <instance - at 0x7fe0c8a96c20>
               args: <tuple - at 0x7fe0d34b7050>
               here: <ImplicitAcquisitionWrapper cresce-o-numero-de-conflitos-e-a-violencia-no-campo-e-a-justica at 0x7fe0c239caa0>
               user: <ImplicitAcquisitionWrapper - at 0x7fe0c1c655f0>
               nothing: <NoneType - at 0x7ad090>
               container: <ImplicitAcquisitionWrapper cresce-o-numero-de-conflitos-e-a-violencia-no-campo-e-a-justica at 0x7fe0c239caa0>
               request: <instance - at 0x7fe0c128eea8>
               wrapped_repeat: <SafeMapping - at 0x7fe0c0667f70>
               traverse_subpath: <list - at 0x7fe0bd342200>
               default: <object - at 0x7fe0d348db30>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper cresce-o-numero-de-conflitos-e-a-violencia-no-campo-e-a-justica at 0x7fe0c239caa0>
               view: <SimpleViewletClass from /home/hvelarde/simples/XYZ/src/collective.nitf/src/collective/nitf/browser/templates/image.pt collective.nitf.image at 0x7fe0bd45fe50>
               translate: <function translate at 0x7fe0bd32a2a8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fe0c1797910>
               options: {...} (0)
               target_language: pt_BR
```

removing five.pt from the project solves the issue.

**Comment by hvelarde** [comment] 2015-08-11 22:32
FYI @rodfersou

**Comment by rodfersou** [comment] 2015-08-13 10:55
@hvelarde what packages breaks with five.pt?

**Comment by hvelarde** [comment] 2015-08-13 12:29
@rodfersou https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/browser/templates/image.pt

**Comment by rodfersou** [comment] 2015-08-14 13:34
@hvelarde need to see what is less annoying.. fix five.pt or fix other packages to create thumbs in the python view file..

**Comment by do3cc** [comment] 2015-08-18 05:47
I remember vaguely that I had this issue too, a long time ago. I only remember my conclusion, that nobody guaranteed that path elements are lists and thus a pop() is not guaranteed to work.
Unfortunately I do not remember where this was and how I fixed it.

**Comment by do3cc** [comment] 2015-08-18 05:59
I remembered it wrong. This is the same bug report:
https://github.com/malthe/chameleon/issues/59

**Comment by hvelarde** [comment] 2015-08-18 11:20
yes, is the same issue.

**Comment by rodfersou** [comment] 2015-08-22 17:24
and if we change:
    image = self.scale(name, furtherPath.pop())
to:
    image = self.scale(name, list(furtherPath).pop())
into plone.app.imaging source?

it looks like an optimization done into chameleon to use tuples instead of a list.. or maybe get rid of pop logic and always try to get the last item like this:
    image = self.scale(name, furtherPath[:-1])
it will try to get the last item if available.

**Comment by rodfersou** [comment] 2015-08-22 17:26
need to check also if `futherPath` variable will be used after this part of code. if yes, we need to update it like `pop` method would do, whithout the last item.

**Comment by rodfersou** [comment] 2015-08-22 17:28
In other words, I think we should fix it into `plone.app.imaging` source.

**Comment by do3cc** [comment] 2015-08-26 08:14
I can't tell you what to do, but if you read the bug malthe/chameleon#59, you will notice that the problem is not with plone.app.imaging. Fixing it in chameleon might be much harder though because it _can_ mean, it gets slower.

**Comment by hvelarde** [comment] 2015-08-26 13:10
I think also this must probably fixed in plone.app.imaging.

**Comment by rodfersou** [comment] 2015-12-02 12:06
Fixed here https://github.com/plone/plone.app.imaging/issues/16

I can't close the issue, can someone do it please?

**Closed** 2015-12-02 12:44 UTC
